version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: skillwise-postgres
    environment:
      POSTGRES_DB: skillwise_db
      POSTGRES_USER: skillwise_user
      POSTGRES_PASSWORD: skillwise_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillwise_user -d skillwise_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local